# Test of ```timeseries_dataset_from_array()```

_Jorge III Altamirano-Astorga_

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from IPython.display import display, Markdown

In [2]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
b = np.arange(99, 79, -1)
b

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80])

In [4]:
c = np.concatenate([a, b]).reshape(20,2)
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [99, 98],
       [97, 96],
       [95, 94],
       [93, 92],
       [91, 90],
       [89, 88],
       [87, 86],
       [85, 84],
       [83, 82],
       [81, 80]])

## Sequence Length 2, Stride 1, Sampling Rate 1

In [5]:
data = tf.keras.utils.timeseries_dataset_from_array(c, None, sequence_length=2, 
                                                 sequence_stride=1,
                                                 sampling_rate=1, batch_size=128,
                                                 shuffle=False, seed=175904,
                                                 start_index=None, end_index=None)
for (i, batch) in enumerate(data):
  inputs = batch
  display(Markdown(f"Sequence number: {i}"))
  print(batch)

Sequence number: 0

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 3  4]
  [ 5  6]]

 [[ 5  6]
  [ 7  8]]

 [[ 7  8]
  [ 9 10]]

 [[ 9 10]
  [11 12]]

 [[11 12]
  [13 14]]

 [[13 14]
  [15 16]]

 [[15 16]
  [17 18]]

 [[17 18]
  [19 20]]

 [[19 20]
  [99 98]]

 [[99 98]
  [97 96]]

 [[97 96]
  [95 94]]

 [[95 94]
  [93 92]]

 [[93 92]
  [91 90]]

 [[91 90]
  [89 88]]

 [[89 88]
  [87 86]]

 [[87 86]
  [85 84]]

 [[85 84]
  [83 82]]

 [[83 82]
  [81 80]]], shape=(19, 2, 2), dtype=int64)


## Sequence Length 3, Stride 1, Sampling Rate 2

In [6]:
data = tf.keras.utils.timeseries_dataset_from_array(c, None, sequence_length=3, 
                                                 sequence_stride=1,
                                                 sampling_rate=2, batch_size=128,
                                                 shuffle=False, seed=175904,
                                                 start_index=None, end_index=None)
for (i, batch) in enumerate(data):
  inputs = batch
  display(Markdown(f"Sequence number: {i}"))
  print(batch)

Sequence number: 0

tf.Tensor(
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]

 [[ 5  6]
  [ 9 10]
  [13 14]]

 [[ 7  8]
  [11 12]
  [15 16]]

 [[ 9 10]
  [13 14]
  [17 18]]

 [[11 12]
  [15 16]
  [19 20]]

 [[13 14]
  [17 18]
  [99 98]]

 [[15 16]
  [19 20]
  [97 96]]

 [[17 18]
  [99 98]
  [95 94]]

 [[19 20]
  [97 96]
  [93 92]]

 [[99 98]
  [95 94]
  [91 90]]

 [[97 96]
  [93 92]
  [89 88]]

 [[95 94]
  [91 90]
  [87 86]]

 [[93 92]
  [89 88]
  [85 84]]

 [[91 90]
  [87 86]
  [83 82]]], shape=(15, 3, 2), dtype=int64)


## Sequence Length 3, Stride 2, Sampling Rate 1

In [7]:
data = tf.keras.utils.timeseries_dataset_from_array(c, None, sequence_length=3, 
                                                 sequence_stride=2,
                                                 sampling_rate=1, batch_size=128,
                                                 shuffle=False, seed=175904,
                                                 start_index=None, end_index=None)
for (i, batch) in enumerate(data):
  inputs = batch
  display(Markdown(f"Sequence number: {i}"))
  print(batch)

Sequence number: 0

tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]

 [[ 9 10]
  [11 12]
  [13 14]]

 [[13 14]
  [15 16]
  [17 18]]

 [[17 18]
  [19 20]
  [99 98]]

 [[99 98]
  [97 96]
  [95 94]]

 [[95 94]
  [93 92]
  [91 90]]

 [[91 90]
  [89 88]
  [87 86]]

 [[87 86]
  [85 84]
  [83 82]]], shape=(9, 3, 2), dtype=int64)


## Sequence Length 4, Stride 2, Sampling Rate 2

In [8]:
data = tf.keras.utils.timeseries_dataset_from_array(c, None, sequence_length=4, 
                                                 sequence_stride=2,
                                                 sampling_rate=2, batch_size=128,
                                                 shuffle=False, seed=175904,
                                                 start_index=None, end_index=None)
for (i, batch) in enumerate(data):
  inputs = batch
  display(Markdown(f"Sequence number: {i}"))
  print(batch)

Sequence number: 0

tf.Tensor(
[[[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 14]]

 [[ 5  6]
  [ 9 10]
  [13 14]
  [17 18]]

 [[ 9 10]
  [13 14]
  [17 18]
  [99 98]]

 [[13 14]
  [17 18]
  [99 98]
  [95 94]]

 [[17 18]
  [99 98]
  [95 94]
  [91 90]]

 [[99 98]
  [95 94]
  [91 90]
  [87 86]]

 [[95 94]
  [91 90]
  [87 86]
  [83 82]]], shape=(7, 4, 2), dtype=int64)
